# Generated by Django 5.1.1 on 2024-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigbluebuttonrecording',
            name='internal_meeting_id',
            field=models.CharField(default=11111, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bigbluebuttonrecording',
            name='recording_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bigbluebuttonroom',
            name='room_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
