# Generated by Django 5.1.1 on 2024-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=255)),
                ('slot_1', models.TimeField()),
                ('slot_2', models.TimeField()),
                ('slot_3', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('remarks', models.TextField(blank=True)),
                ('coordinator_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
