# Generated by Django 5.1.1 on 2024-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_data', '0002_externallead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallead',
            name='slot_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallead',
            name='slot_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externallead',
            name='slot_3',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
