# Generated by Django 5.1.1 on 2024-10-05 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MESSAGE', 'New Message'), ('ABSENCE', 'Student Absence'), ('TRAINER_ABSENT', 'Trainer Absent'), ('COURSE_ENDING', 'Course Ending'), ('COURSE_HOLD_REQUEST', 'Course Hold Request'), ('COURSE_HOLD_DECISION', 'Course Hold Decision'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_DECISION', 'Leave Decision'), ('NEW_STUDY_MATERIAL', 'New Study Material'), ('FEEDBACK_SUBMISSION', 'Feedback Submission'), ('TRAINER_ASSIGNMENT', 'Trainer Assignment'), ('NEW_NOTICE', 'New Notice')], max_length=25),
        ),
    ]
